### ISSUE TITLE
Issues with linked templates

### ISSUE THREAD

**Issue by JonAnder83** [diasdmhub/Zabbix_Template_Asus_Merlin#1]
Hi! First of all: Thanks for your work! I'm really looking forward to make this work on my RT-AC68U.

I'm running into a couple of issues.

First of all, if I try to import the template as is, zabbix does not recognize any of the linked templates unless I rename them:

Template App SSH Service -> SSH Service
Template Module ICMP Ping -> ICMP Ping
Template Module Linux block devices by Zabbix agent -> Linux block devices by Zabbix agent
Template Module Linux filesystems by Zabbix agent -> Linux filesystems by Zabbix agent
Template Module Linux memory by Zabbix agent -> Linux memory by Zabbix agent
Template Module Linux network interfaces by Zabbix agent -> Linux network interfaces by Zabbix agent
Template Module Zabbix agent -> Zabbix agent

Then, I solve the template dependency issues, however, a new issue arises: 

vm.memory.size[webui,total]

Key is not recognised.

However, these are the available items for "Linux memory by Zabbix agent" template:

vm.memory.size[available]
vm.memory.size[pavailable]
system.swap.size[,free]
system.swap.size[,pfree]
vm.memory.utilization
vm.memory.size[total]
system.swap.size[,total]

I'm on Zabbix 5.2.5, on arch linux.

I can help troubleshoot and fix this if you ask me to and suggest a way to do so,

Thanks!

**Comment by diasdmhub** [comment]
Thanks for your reply @JonAnder83.

The linked templates are all Out-of-box Templates (OOTB) provided by the Zabbix team. So, their names are standard after initial installation.
Changing OOTB template names before importing Asus template might cause this dependency issue you experienced.
Also, if you upgraded your Zabbix, any new OOTB template will not be updated unless you manually do it.

Please check [Zabbix OOTB templates documentation](https://www.zabbix.com/documentation/current/manual/config/templates_out_of_the_box) for more information.

As for "vm.memory.size[webui,total]" key, it is dependent of "vm.memory.size[total]" key. Somehow it got lost while exporting the template. I'm looking at this issue right now. 

Thanks again for your feedback.

**Comment by diasdmhub** [comment]
Ohh. I see now.
As mentioned above, the provided "vm.memory.size[webui,total]" key depends on "Total Memory" item, wich is provided by "Template Module Linux memory by Zabbix agent".

Since you had different OOTB template names in your Zabbix, I figure "Memory WebUI Total" item could not find "Total memory" master item.
By re-linking your templates to the correct name, as you already did, should resolve that issue. You could also re-configure "Memory WebUI Total" master item.

As far as I understend, it is a expected behavior.

**Comment by diasdmhub** [comment]
Thanks a lot for the heads up Jon.

Checking [Zabbix Git](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates), I saw there was a big change in naming scheme of templates and that doesn't seem to be mentioned in [Zabbix's "What's new" documentation page](https://www.zabbix.com/documentation/current/manual/installation/template_changes).

Prior to [version 5.0, OOTB templates](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates?at=refs%2Fheads%2Frelease%2F5.0) had "Template" term as a prefix in the name.
```
<templates>
      <template>
         <template>Template Module ICMP Ping</template>
         <name>Template Module ICMP Ping</name>
```

With version 5.2, it seems that the prefix was ditched and now uses a _.yaml_ file format, instead of _.xml_.
```
templates:
    -
      template: 'ICMP Ping'
      name: 'ICMP Ping'
```

Since I created this template before using Zabbix 5.2, I did not foresee that change.
But, with your help I was a little unrest and could see the changes. Thank you.

As for item "Memory WebUI Used", it uses the following calculated Formula:
`last("vm.memory.size[webui,total]")-last("vm.memory.size[free]")`
```
<item>
    <name>Memory WebUI Used</name>
    <type>CALCULATED</type>
    <key>vm.memory.size[webui,used]</key>
    <history>7d</history>
    <units>B</units>
    <params>last(&quot;vm.memory.size[webui,total]&quot;)-last(&quot;vm.memory.size[free]&quot;)</params>
    <description>Used memory in Bytes. Webui used = Webui total - Webui free</description>
    <applications>
        <application>
            <name>Memory</name>
        </application>
    </applications>
</item>
```

I'm glad you could "patch" the template to your setup.
In the near future I'll try to update those templates names. Please, keep watching.

I really appreciate your feedback and hope to see more of your insights.
Best regards.

**Comment by JonAnder83** [comment]
Sure, I will keep an eye on your work. It's pretty cool.

Regards!
